services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "default_secret"
      MERCH_DB_DSN: "postgres://postgres:postgres@db:5432/merch?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "merch"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d merch"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: 
      - "-path=/migrations"
      - "-database=postgres://postgres:postgres@db:5432/merch?sslmode=disable"
      - "up"
    depends_on:
      db:
        condition: service_healthy

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./seed"]
    environment:
      JWT_SECRET: "default_secret"
      MERCH_DB_DSN: "postgres://postgres:postgres@db:5432/merch?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data: